//
// Created by jack on 12/21/21.
//

#ifndef CHESSENGINE_DIRECTION_H
#define CHESSENGINE_DIRECTION_H


enum Direction {
    NORTH=-8, EAST=1, SOUTH=8, WEST=-1, NORTHEAST=-7, NORTHWEST=-9, SOUTHEAST=9, SOUTHWEST=7
};


#endif //CHESSENGINE_DIRECTION_H
